//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatorKlubs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public Clients()
        {
            this.Session_Log = new HashSet<Session_Log>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string E_mail { get; set; }
        public int Age { get; set; }
    
        public virtual ICollection<Session_Log> Session_Log { get; set; }
    }
}
