//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatorKlubs
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatorKlubsEntities : DbContext
    {
        public DatorKlubsEntities()
            : base("name=DatorKlubsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public static DatorKlubsEntities _context;
        public static DatorKlubsEntities GetContext()
        {
            if (_context == null)
            {
                _context = new DatorKlubsEntities();
            }
            return _context;
        }


        public DbSet<Clients> Clients { get; set; }
        public DbSet<Computers> Computers { get; set; }
        public DbSet<Session_Log> Session_Log { get; set; }
        public DbSet<Workers> Workers { get; set; }
    }
}
